# Generated by Django 4.0.1 on 2022-11-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fechahora', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('contenido', models.TextField()),
                ('enviado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Contactanos',
                'ordering': ['-fechahora'],
            },
        ),
    ]
