# Generated by Django 4.0.1 on 2022-11-04 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Areas del Derecho',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Juez',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellidos', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Jueces',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'Salas de la Corte Suprema',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Casacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=40, unique=True)),
                ('materia', models.CharField(max_length=100)),
                ('sumilla', models.TextField(blank=True, null=True)),
                ('extracto', models.TextField(blank=True, null=True)),
                ('demandante', models.CharField(max_length=130)),
                ('demandado', models.CharField(max_length=250)),
                ('parte', models.IntegerField(blank=True, choices=[(1, 'Demandante'), (2, 'Demandado'), (3, 'Ambos')], default=1, null=True)),
                ('casante', models.CharField(max_length=250)),
                ('es_precedente', models.BooleanField(default=False)),
                ('fallo', models.IntegerField(choices=[(1, 'Improcedente'), (2, 'Infundado'), (3, 'Fundado en Parte'), (4, 'Fundado')], default=1)),
                ('juezponente_nombre', models.CharField(max_length=100)),
                ('jueces_nombres', models.CharField(max_length=150)),
                ('juezdiscordia_nombre', models.CharField(max_length=50)),
                ('boletin', models.CharField(blank=True, max_length=60, null=True)),
                ('pagina', models.CharField(blank=True, max_length=17, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_sentencia', models.DateField(blank=True, null=True)),
                ('texto', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('area', models.ManyToManyField(blank=True, to='juri.Area')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juri.sala')),
            ],
            options={
                'verbose_name_plural': 'Casaciones',
            },
        ),
    ]
